package com.autogeneral.techtest.angservice.model.db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ToDo")
public class ToDo {

	private String id;
	private String text;
	private Boolean completed;
	private String createdAt;

	public ToDo() {
	}

	public ToDo(String text, Boolean completed, String createdAt) {
		this.text = text;
		this.completed = completed;
		this.createdAt = createdAt;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "Id")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "Text")
	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@DynamoDBAttribute(attributeName = "Completed")
	public Boolean getCompleted() {
		return completed;
	}

	public void setCompleted(Boolean completed) {
		this.completed = completed;
	}

	@DynamoDBAttribute(attributeName = "CreatedAt")
	public String getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	@Override
	public String toString() {
		return "ToDo{" +
				"id='" + id + '\'' +
				", text='" + text + '\'' +
				", completed=" + completed +
				", createdAt='" + createdAt + '\'' +
				'}';
	}
}